version: 1
models:
  models: 
    - 'openai/gpt-3.5-turbo'
    - 'anthropic/claude-v1'
  temperature: 0.7
  max_tokens: 100
  top_p: 1.0
  top_k: 40
expect:
  max_elapsed_time: 3.3
  min_response_length: 100
  max_response_length: 200
  match:
    - /independent/i
    - /smart/i
  