#!/usr/bin/env python3.10

import os
import sys

sys.path.append('.')
sys.path.append('/opt/conda/lib/python3.10/site-packages')

import argparse
from dotenv import load_dotenv
load_dotenv()

from rich import print
from rich.console import Console
from rich.panel import Panel

from .utils.run import run_prompt_with_args

parser = argparse.ArgumentParser(description="Run a prompt against configured models.",
                                formatter_class=argparse.ArgumentDefaultsHelpFormatter)

parser.add_argument('--abbrev', help="Abbreviate prompts and completions", action=argparse.BooleanOptionalAction, default=True)
parser.add_argument('--cooldown', '-c', help="How much to wait after a re-run", default=5)
parser.add_argument("--model", "-m", help="Model to use if none is configured (defaults to DEFAULT_MODEL environment variable)", default=os.environ.get('DEFAULT_MODEL'))
parser.add_argument("prompt_path", help="Path to prompt to run")

args = parser.parse_args()
parsed_args = vars(args)

run_prompt_with_args(parsed_args)