version: 1
models:
  gpt4crazy:
    model: 'openai/gpt-4'
    temperature: 0.99
  claudev1smart:
    model: 'anthropic/claude-v1'
    temperature: 0
  all:
    temperature: 0.7
    max_tokens: 64
expect:
  max_elapsed_time: 3.3
  min_response_length: 100
  max_response_length: 200
  match:
    name: /independent/i
  